# app/config/exports.py
"""
Exports Module
Экспорт всех констант для обратной совместимости
"""

from app.config import config


TELEGRAM_BOT_TOKEN = config.TELEGRAM_BOT_TOKEN
TELEGRAM_TOKEN = config.TELEGRAM_BOT_TOKEN
BOT_TOKEN = config.TELEGRAM_BOT_TOKEN
TELEGRAM_CHANNEL_ID = config.TELEGRAM_CHANNEL_ID
CHAT_ID = config.TELEGRAM_CHANNEL_ID
CHANNEL_ID = config.TELEGRAM_CHANNEL_ID
ADMIN_CHAT_ID = config.ADMIN_CHAT_ID

GEMINI_API_KEY = config.GEMINI_API_KEY
OPENAI_API_KEY = config.OPENAI_API_KEY
ANTHROPIC_API_KEY = config.ANTHROPIC_API_KEY

ETHERSCAN_API_KEY = config.ETHERSCAN_API_KEY
BSCSCAN_API_KEY = config.BSCSCAN_API_KEY
POLYGONSCAN_API_KEY = config.POLYGONSCAN_API_KEY
ARBISCAN_API_KEY = config.ARBISCAN_API_KEY
BASESCAN_API_KEY = config.BASESCAN_API_KEY
SNOWTRACE_API_KEY = config.SNOWTRACE_API_KEY
OPTIMISM_ETHERSCAN_API_KEY = config.OPTIMISM_ETHERSCAN_API_KEY
FTMSCAN_API_KEY = config.FTMSCAN_API_KEY
HELIUS_API_KEY = config.HELIUS_API_KEY
SOLSCAN_API_KEY = config.SOLSCAN_API_KEY

COINGECKO_API_KEY = config.COINGECKO_API_KEY
ALCHEMY_API_KEY = config.ALCHEMY_API_KEY
COINMARKETCAP_API_KEY = config.COINMARKETCAP_API_KEY
CRYPTOPANIC_API_KEY = config.CRYPTOPANIC_API_KEY
NEWSAPI_KEY = config.NEWSAPI_KEY
DEXSCREENER_API_KEY = config.DEXSCREENER_API_KEY
BIRDEYE_API_KEY = config.BIRDEYE_API_KEY

RSS_FEEDS = {name: feed.url for name, feed in config.RSS_FEEDS.items()}
POST_DELAY_SECONDS = config.POST_DELAY_SECONDS
IDLE_DELAY_SECONDS = config.IDLE_DELAY_SECONDS
DB_PATH = str(config.DB_PATH)
NEWS_DB_PATH = str(config.NEWS_DB_PATH)
MIN_IMAGE_WIDTH = config.MIN_IMAGE_WIDTH
MIN_IMAGE_HEIGHT = config.MIN_IMAGE_HEIGHT
COMMON_HEADERS = config.COMMON_HEADERS

NEWS_SOURCES = [
    {
        'name': name,
        'url': feed.url,
        'priority': feed.priority,
        'category': feed.category,
        'language': feed.language,
        'enabled': feed.enabled
    }
    for name, feed in config.RSS_FEEDS.items()
]

FETCH_INTERVAL = config.FETCH_INTERVAL
NEWS_CHECK_INTERVAL = config.NEWS_CHECK_INTERVAL
POSTS_PER_HOUR_CAP = config.POSTS_PER_HOUR_CAP
MIN_CONFIDENCE_SCORE = config.MIN_CONFIDENCE_SCORE

ENABLED_CHAINS = config.ENABLED_CHAINS
MIN_USD = config.MIN_USD

WHALE_ENABLED = config.WHALE_ENABLED
NEWS_ENABLED = config.NEWS_ENABLED
ANALYTICS_ENABLED = config.ANALYTICS_ENABLED
TRADING_ENABLED = config.TRADING_ENABLED
HYPERLIQUID_ENABLED = config.HYPERLIQUID_ENABLED

DATA_DIR = config.DATA_DIR
STATE_FILE = config.STATE_FILE
WALLET_DB_JSON_PATH = config.WALLET_DB_JSON_PATH

LOG_LEVEL = config.LOG_LEVEL
HEALTH_CHECK_ENABLED = config.HEALTH_CHECK_ENABLED

PORT = config.PORT
HTTP_TIMEOUT = config.HTTP_TIMEOUT
RPC_TIMEOUT = config.RPC_TIMEOUT
WEBHOOK_TIMEOUT = config.WEBHOOK_TIMEOUT
MAX_MEMORY_MB = config.MAX_MEMORY_MB


__all__ = [
    'TELEGRAM_BOT_TOKEN',
    'TELEGRAM_TOKEN',
    'BOT_TOKEN',
    'TELEGRAM_CHANNEL_ID',
    'CHAT_ID',
    'CHANNEL_ID',
    'ADMIN_CHAT_ID',
    'GEMINI_API_KEY',
    'OPENAI_API_KEY',
    'ANTHROPIC_API_KEY',
    'ETHERSCAN_API_KEY',
    'BSCSCAN_API_KEY',
    'POLYGONSCAN_API_KEY',
    'ARBISCAN_API_KEY',
    'BASESCAN_API_KEY',
    'SNOWTRACE_API_KEY',
    'OPTIMISM_ETHERSCAN_API_KEY',
    'FTMSCAN_API_KEY',
    'HELIUS_API_KEY',
    'SOLSCAN_API_KEY',
    'COINGECKO_API_KEY',
    'ALCHEMY_API_KEY',
    'COINMARKETCAP_API_KEY',
    'CRYPTOPANIC_API_KEY',
    'NEWSAPI_KEY',
    'DEXSCREENER_API_KEY',
    'BIRDEYE_API_KEY',
    'RSS_FEEDS',
    'NEWS_SOURCES',
    'FETCH_INTERVAL',
    'NEWS_CHECK_INTERVAL',
    'POSTS_PER_HOUR_CAP',
    'MIN_CONFIDENCE_SCORE',
    'POST_DELAY_SECONDS',
    'IDLE_DELAY_SECONDS',
    'DB_PATH',
    'NEWS_DB_PATH',
    'DATA_DIR',
    'STATE_FILE',
    'WALLET_DB_JSON_PATH',
    'MIN_IMAGE_WIDTH',
    'MIN_IMAGE_HEIGHT',
    'COMMON_HEADERS',
    'ENABLED_CHAINS',
    'MIN_USD',
    'WHALE_ENABLED',
    'NEWS_ENABLED',
    'ANALYTICS_ENABLED',
    'TRADING_ENABLED',
    'HYPERLIQUID_ENABLED',
    'LOG_LEVEL',
    'HEALTH_CHECK_ENABLED',
    'PORT',
    'HTTP_TIMEOUT',
    'RPC_TIMEOUT',
    'WEBHOOK_TIMEOUT',
    'MAX_MEMORY_MB',
]