# app/__init__.py
"""
Crypto Compass Application Package
Version: 4.2.0
Main application initialization module
"""

__version__ = "4.2.0"
__author__ = "Crypto Compass Team"

from app.config import (
    config,
    Config,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHANNEL_ID,
    ADMIN_CHAT_ID,
    ETHERSCAN_API_KEY,
    BSCSCAN_API_KEY,
    POLYGONSCAN_API_KEY,
    ARBISCAN_API_KEY,
    BASESCAN_API_KEY,
    HELIUS_API_KEY,
    COINGECKO_API_KEY,
    OPENAI_API_KEY,
    GEMINI_API_KEY,
    ANTHROPIC_API_KEY,
    RSS_FEEDS,
    NEWS_SOURCES,
    ENABLED_CHAINS,
    MIN_USD,
    WHALE_ENABLED,
    NEWS_ENABLED,
    ANALYTICS_ENABLED,
    TRADING_ENABLED,
    DB_PATH,
    NEWS_DB_PATH,
    DATA_DIR,
    LOG_LEVEL,
    PORT,
    HTTP_TIMEOUT,
    RPC_TIMEOUT,
    WEBHOOK_TIMEOUT,
    POST_DELAY_SECONDS,
    IDLE_DELAY_SECONDS,
    FETCH_INTERVAL,
    NEWS_CHECK_INTERVAL,
)

__all__ = [
    "__version__",
    "config",
    "Config",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHANNEL_ID",
    "ADMIN_CHAT_ID",
    "ETHERSCAN_API_KEY",
    "BSCSCAN_API_KEY",
    "POLYGONSCAN_API_KEY",
    "ARBISCAN_API_KEY",
    "BASESCAN_API_KEY",
    "HELIUS_API_KEY",
    "COINGECKO_API_KEY",
    "OPENAI_API_KEY",
    "GEMINI_API_KEY",
    "ANTHROPIC_API_KEY",
    "RSS_FEEDS",
    "NEWS_SOURCES",
    "ENABLED_CHAINS",
    "MIN_USD",
    "WHALE_ENABLED",
    "NEWS_ENABLED",
    "ANALYTICS_ENABLED",
    "TRADING_ENABLED",
    "DB_PATH",
    "NEWS_DB_PATH",
    "DATA_DIR",
    "LOG_LEVEL",
    "PORT",
    "HTTP_TIMEOUT",
    "RPC_TIMEOUT",
    "WEBHOOK_TIMEOUT",
    "POST_DELAY_SECONDS",
    "IDLE_DELAY_SECONDS",
    "FETCH_INTERVAL",
    "NEWS_CHECK_INTERVAL",
]